# Built with Jekyll 3.2.0

# Setup
title:               Nick Henscheid
tagline:             'Mathematician'
description:         ''
url:                 'http://127.0.0.1:4000/site'
baseurl:             '/site'
excerpt_separator:   <!--more-->
# highlighter: rogue


# About/contact
author:
  name:              Nick Henscheid
  url:               nhenscheid.github.io
  email:             nick.henscheid@gmail.com

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  posts:
    output: true
    permalink: /:collection/:path/

  research:
    output: true
    permalink: /:collection/:path/

  teaching: 
    output: true
    permalink: /:collection/:path/

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM
  syntax_highlighter: rouge

# Custom vars
version:             1.0

# Exclusions from the final site
include: ["_research","_teaching"]
exclude: [optional, vendor,unused]


